
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package features;

import features.Classes.User;
import features.info.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        User u = new User("rook103", "xbox");
        addUser(u);
    }

    public static void addUser(User u) {
        String p = " ";
        ArrayList<String> prev = new ArrayList<String>();

        // Read everything previously in file
        try {
            BufferedReader br = new BufferedReader(
                    new FileReader("C:\\Users\\terra\\features\\app\\src\\main\\java\\features\\info\\users.txt"));
            p = br.readLine();
            while (p != null) {
                prev.add(p);
                p = br.readLine();
            }
            br.close();
            System.out.println(p);
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Add new line
        String a = "";
        try {
            BufferedWriter b = new BufferedWriter(
                    new FileWriter("C:\\Users\\terra\\features\\app\\src\\main\\java\\features\\info\\users.txt"));
            for (int i = 0; i < prev.size(); i++) {
                a += prev.get(i) + "\n";
            }
            a += "Username: " + u.getUsername() + " | Password- " + u.getPassword() + "\n";
            b.write(a);
            b.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
